In [8]:
import pandas as pd
import numpy as np
import sympy as sym
from scipy.stats import pearsonr

import matplotlib.pyplot as plt


from tqdm.auto import tqdm
from IPython.display import display

In [53]:
A = np.array([[2,4],[-1,3],[0,-2]])

U, s, Vt = np.linalg.svd(A)

Sigma = np.diag(s)
sym.Matrix(Sigma)

Matrix([
[5.47722557505166, 0.0],
[             0.0, 2.0]])

In [57]:
Sigma_plus = np.zeros(A.T.shape)
Sigma_plus[0,0] = 1/ s[0]
Sigma_plus[1,1] = 1/ s[1]
print(Sigma_plus)


A_plus = Vt.T@Sigma_plus@U.T

sym.Matrix(A_plus)

[[0.18257419 0.         0.        ]
 [0.         0.5        0.        ]]


Matrix([
[ 0.316666666666667, -0.366666666666667,  0.0833333333333334],
[0.0833333333333333,  0.166666666666667, -0.0833333333333333]])

In [64]:
AplusA = A_plus@A
AAplus = A@A_plus


sym.Matrix(AplusA)  
sym.Matrix(AAplus)

Matrix([
[  0.966666666666667, -0.0666666666666665, -0.166666666666667],
[-0.0666666666666666,   0.866666666666667, -0.333333333333333],
[ -0.166666666666667,  -0.333333333333333,  0.166666666666667]])

In [68]:
GLS = np.array([[3,4,0],[3,-1,0],[2,0,0]])
y = np.array([[1,2,3]])

nl = A_plus @ y.T
nl


array([[-0.16666667],
       [ 0.16666667]])

In [72]:
At = np.array([[3,0,0,-1], [0,3,-1,0],[0,-1,3,0],[-1,0,0,3]])

A = At.T
A

array([[ 3,  0,  0, -1],
       [ 0,  3, -1,  0],
       [ 0, -1,  3,  0],
       [-1,  0,  0,  3]])

In [76]:
ew, V = np.linalg.eig(A)

ew, V

(array([4., 2., 4., 2.]),
 array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
        [ 0.        ,  0.        , -0.70710678,  0.70710678],
        [ 0.        ,  0.        ,  0.70710678,  0.70710678],
        [-0.70710678,  0.70710678,  0.        ,  0.        ]]))